apiVersion: v1
kind: Service
metadata: 
  name: postgres-operator
  namespace: otus
  labels:
    app: postgres-operator
spec: 
  type: ClusterIP
  ports:
    - port: 9187
      targetPort: 9187
      name: pmetrics
  selector: 
    app: postgres-operator