apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userservice-monitor
  namespace: monitoring
  labels:
    app: userservice-monitor
    
spec:
  endpoints:
    - port: {{ .Values.monitoring.portName }}
      interval: {{ .Values.monitoring.interval }}
      path: {{ .Values.monitoring.path }}     
  selector:
    matchLabels:
      app: userservice
  namespaceSelector:
    # matchNames:
    # - default
    any: true
  
