{
 "title": "UserService",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency 50%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{controller=\"Users\"}[1m])) by (le, action))*1000",
     "legendFormat": "{{action}}, ms"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"userservice-release\"}[1m])) by (le))*1000",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "Latency 95%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{controller=\"Users\"}[1m])) by (le, action))*1000",
     "legendFormat": "{{action}}, ms"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"userservice-release\"}[1m])) by (le))*1000",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "Latency 99%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{controller=\"Users\"}[1m])) by (le, action))*1000",
     "legendFormat": "{{action}}, ms"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"userservice-release\"}[1m])) by (le))*1000",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (action) (rate(http_requests_received_total{controller = \"Users\"}[1m]))",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"userservice-release\"}[1m]))",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "ErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller=\"Users\", code=~\"5.+\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "sum (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"otus\", container=\"userservice\"}/(1024*1024)",
     "legendFormat": "{{pod}}, mb"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"userservice\"}[3m])",
     "legendFormat": "{{pod}}, mb"
    }
   ]
  },
  {
   "title": "DB Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{container=\"postgres-operator-app\"}[5m])/(1024))",
     "legendFormat": "resident mem, kB"
    }
   ]
  },
  {
   "title": "DB CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{container=\"postgres-operator-app\"}[1m]))",
     "legendFormat": "db"
    }
   ]
  },
  {
   "title": "Fetch (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"my-db\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}