apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userservice-monitor
  labels:
    app: userservice-monitor
    
spec:
  endpoints:
    - port: http
      interval: 15s
      path: /metrics     
  selector:
    matchLabels:
      app: userservice
  
